tap "caskroom/cask"
tap "caskroom/versions"
tap "cjbassi/gotop"
tap "dart-lang/dart"
tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "cocoapods"
brew "docker"
brew "git"
brew "git-lfs"
brew "python"
brew "go"
brew "htop"
brew "hub"
brew "usbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "ios-deploy"
brew "node"
brew "joplin"
brew "mas"
brew "neofetch"
brew "pipenv"
brew "pyenv"
brew "pyenv-virtualenv"
brew "r"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "cjbassi/gotop/gotop"
brew "dart-lang/dart/dart"
brew "getantibody/tap/antibody"
cask "alfred"
cask "dash"
cask "docker"
cask "dropbox"
cask "evernote"
cask "fastlane"
cask "font-fira-code"
cask "google-backup-and-sync"
cask "google-chrome"
cask "hyper"
cask "karabiner-elements"
cask "miniconda"
cask "slack"
cask "spotify"
cask "ticktick"
cask "virtualbox"
cask "visual-studio-code"
mas "Compressor", id: 424390742
mas "Final Cut Pro", id: 424389933
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Motion", id: 434290957
mas "Pixelmator Pro", id: 1289583905
mas "Xcode", id: 497799835
